-- ESSE PROCEDURE É APENAS UM EXEMPLO NÃO É POSSIVEL COMPILAR POR CAUSA DOS COMENTÁRIOS
DELIMITER // -- TROCO O ; POR // PARA PODER USAR ; NA PROGRAMAÇÃO DO PROCEDURE
CREATE PROCEDURE TESTE (IN X INT, OUT Y VARCHAR(30)) -- CRIO UM PROCEDURE COM ENTRADA X E SAIDA Y
BEGIN -- INICIO A PROCEDURE
DECLARE VARIAVEL INT default 0; -- DECLARAÇÃO DE VARIAVEL INICIALIZANDO COM 0 SE NÃO INICIALIZAR ESTÁ COM NULL

SET VARIAVEL = 0; -- OUTRA MANEIRA DE SETAR VALOR EM UMA VARIAVEL

	IF(X > 100) THEN -- INICIO DE ESTRUTURA IF
		SET Y = 'VALOR INVÁLIDO'; 
	ELSE
		SELECT NMEMPREGADO INTO Y FROM EMPREGADO WHERE CDEMPREGADO = X;	
	END IF; -- FIM DA ESTRUTURA
END// -- FINALIZA A PROGRAMAÇÃO DA PROCEDURE

DELIMITER ;  -- VOLTA DE // PARA ;

CALL TESTE(1, @SEL); -- EXECUTA A PROCEDURE PASSANDO OS PARÂMETROS, @SEL É UA VARIÁVEL TEMPORÁRIA
SELECT @SEL; -- EXIBE O CONTEUDO DA VARIAVEL TEMPORÁRIA

-- EXERCÍCIO 1
-- CRIAR UMA PROCEDURE CHAMADA AULA QUE RECEBE COMO PRIMEIRO PARÂMETRO O CÓDIGO DO EMPREGADO E DEVOLVE
-- NO SEGUNDO PARÊMETRO UMA FRASE NA SEGUINTE REGRA:
-- CASO O SALÁRIO DO EMPREGADO SEJA MAIOR QUE A MÉDIA DEVOLVE 'ACIMA DA MÉDIA'
-- CASO O SALÁRIO DO EMPREGADO SEJA MENOR QUE A MÉDIA DEVOLVE 'ABAIXO DA MEDIA'

DELIMITER //
CREATE PROCEDURE AULA (IN CODEMP INT, OUT RES VARCHAR(15))
begin
DECLARE MEDIA double;
DECLARE SALARIO double;

	SELECT AVG(VLSALARIO) INTO MEDIA FROM empregado;
	SELECT VLSALARIO INTO SALARIO FROM EMPREGADO WHERE CDEMPREGADO = CODEMP;

	IF(SALARIO > MEDIA) then
		SET RES = 'ACIMA DA MÉDIA';
	ELSE
		SET RES = 'ABAIXO DA MÉDIA';
	END IF;

END//
DELIMITER ;

CALL AULA(1, @RES);
SELECT @RES;

-- CRIE UMA PROCEDURE CHAMADA SOMATORIA QUE RECEBE COMO PRIMEIRO PARÂMETROUM NÚMERO
-- MENOR QUE 100 E COMO SEGUNDO PARÂMETRO UM NUMERO MENOR DE 20, E DEVOLVE NO 
-- NO TERCEIRO PARÂMETRO O RESULTADO DO PRIMEIRO SOMADO A ELE O NÚMERO DE VEZES
-- DO SEGUNDO PARÂMETRO

-- WHILE CONDIÇÃO DO
-- .............;
-- .............;
-- END while;

DROP PROCEDURE IF EXISTS SOMATORIA;
DELIMITER //
CREATE PROCEDURE SOMATORIA(IN NUM1 INT, IN NUM2 INT, OUT RES INT)
BEGIN
DECLARE COUNT INT DEFAULT 0;
DECLARE TMP INT DEFAULT 0;
	IF(NUM1 < 100 && NUM2 < 20) THEN
		WHILE(COUNT < NUM2) DO	
			SET TMP = TMP + NUM1;
			SET COUNT = COUNT +1;
		END WHILE;
	ELSE
		SET RES = -1;
	END IF;
	SET RES = TMP;
END//
DELIMITER ;

CALL SOMATORIA(2,3,@RES);
SELECT @RES;