#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
# PICDEM_FSUSB configuration
CND_ARTIFACT_DIR_PICDEM_FSUSB=dist/PICDEM_FSUSB/production
CND_ARTIFACT_NAME_PICDEM_FSUSB=MPLAB.X.production.hex
CND_ARTIFACT_PATH_PICDEM_FSUSB=dist/PICDEM_FSUSB/production/MPLAB.X.production.hex
CND_PACKAGE_DIR_PICDEM_FSUSB=${CND_DISTDIR}/PICDEM_FSUSB/package
CND_PACKAGE_NAME_PICDEM_FSUSB=mplab.x.tar
CND_PACKAGE_PATH_PICDEM_FSUSB=${CND_DISTDIR}/PICDEM_FSUSB/package/mplab.x.tar
